lang: es

project:
  output-dir: docs

website:
  navbar:
    left:
      - href: ./pt/index.html
        text: "PT"
      - href: ./en/index.html
        text: EN  
      - href: /index.html
        text: "**ES**"    
      - text: "Principal"
        href: /index.html
      - text: Sobre LatinR
        menu:        
          - text: "Equipo Organizador"
            href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/index.qmd
          - href: sobre/coc/index.qmd
          - href: sobre/ediciones-anteriores/index.qmd  
      - text: Participa
        menu: 
          - text: "Llamado a presentación de trabajos"
            href: blog/es/2024-07-09-presentacion-trabajos-2024.html
          - text: "Sobre la Inscripción"
            href: blog/es/2024-08-01-inscripcion.html 
          - text: "Inscripción"
            href: https://www.eventbrite.cl/e/latinr-2024-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-970622687587?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl
           
      # - text: LatinR 2024
      #   menu: 
      #     - text: "Lugar"
      #       href: cronograma/lugar/index.qmd 
      #     - text: "Recursos turísticos"
      #       href: cronograma/recursos-turisticos/index.qmd  
      #     - text: "Becas de asistencia"
      #       href: blog/es/2023-08-18-becas-2023.html    
      # - text: Programa
      #   menu: 
          # - text: "Programa resumido"
          #   href: cronograma/programa/preliminar.qmd 
          # - text: "Calendario"
          #   href: cronograma/programa/index.qmd            
          # - text: "Conferencistas"
          #   href: cronograma/conferencistas/index.qmd    
          # - text: "Tutoriales"
          #   href: cronograma/tutoriales/index.qmd                 
          # - text: "Presentaciones"
          #   href: cronograma/programa/presentaciones.qmd 
          # - text: "Posters"
          #   href: cronograma/programa/posters.qmd              
      - text: "Novedades"
        href: blog/es/index.html          
      - text: "Ediciones anteriores"
        menu:
        - text: "2023"
          href: https://2023.latinr.org/
        - text: "2022"
          href: https://2022.latinr.org/
        - text: "2021"
          href: https://2021.latinr.org/
        - text: "2020"
          href: https://2020.latinr.org/
        - text: "2019"
          href: https://2019.latinr.org/
        - text: "2018"
          href: https://2018.latinr.org/