lang: pt

project:
  output-dir: docs/pt

website:
  navbar:
    left:
      - href: /index.html
        text: "**PT**"
      - href: ../en/index.html
        text: EN  
      - href: ../index.html
        text: ES      
      - text: "Página inicial"
        href: /index.html
      - text: Sobre a LatinR
        menu:        
          - text: "Equipe organizadora"
            href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/apoio.qmd
          - href: sobre/coc/codigo-de-conduta.qmd
          - href: sobre/ediciones-anteriores/edicoes-anteriores.qmd     
      - text: Participe
        menu: 
          - text: "Chamada para submissão de trabalhos"
            href: blog/pt/2024-07-09-apresentacao-trabalhos-2024.html
          - text: "Inscrição"
            href: https://www.eventbrite.cl/e/latinr-2024-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-970622687587?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl
          - text: "Preços de inscrição"
            href: blog/pt/2024-08-01-inscricao.qmd
      # - text: LatinR 2024
      #   menu: 
      #     - text: "Localização"
      #       href: cronograma/lugar/lugar-pt.qmd    
      #     - text: "Recursos turísticos"
      #       href: cronograma/recursos-turisticos/index-pt.qmd  
      #     - text: "Bolsas"
      #       href: blog/pt/2023-08-18-bolsas-2023.html    
      # - text: Programa
      #   menu: 
          # - text: "Programa resumido"
          #   href: cronograma/programa/preliminar.qmd 
          # - text: "Calendário"
          #   href: cronograma/programa/index.qmd            
          # - text: "Palestras convidadas"
          #   href: cronograma/conferencistas/palestras-convidadas.qmd    
          # - text: "Workshops"
          #   href: cronograma/tutoriales/workshops-pt.qmd                 
          # - text: "Apresentações"
          #   href: cronograma/programa/presentaciones.qmd 
          # - text: "Pôsters"
          #   href: cronograma/programa/posters.qmd               
      - text: "Novidades"
        href: blog/pt/index.html   
      - text: Edições anteriores
        menu:
        - text: "2023"
          href: https://2023.latinr.org/
        - text: "2022"
          href: https://2022.latinr.org/
        - text: "2021"
          href: https://2021.latinr.org/
        - text: "2020"
          href: https://2020.latinr.org/
        - text: "2019"
          href: https://2019.latinr.org/
        - text: "2018"
          href: https://2018.latinr.org/